#! /bin/bash
echo "Enter password:"
read password
echo $password

if [ "$password" = "john" ];then
	echo "Hello John"
elif [ "$password" = "mike" ];
then
	echo "Hello Mike"
elif [ "$password" = lewis ]
then
	echo "Hello Lewis"
else
	echo "I don't know you,go away"
fi
