#!/bin/bash

echo -n "Enter a number(n>0):"

while read num
do
	if [ $num -le 0 ]
	then
		echo "Please enter a number greater than 0."
	else
		sum=0
		while [ $num -gt 0 ]
		do
			sum=$[ $sum + $num ]
			let num=$num-1
		done
		echo "summary is {num} is $sum"
	fi
	echo -n "Enter a number(n>0):"
done
		
